import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { runInNewContext } from 'node:vm';
import ts from 'typescript';
import * as React from 'react';
import * as jsx from 'react/jsx-runtime';
import { renderToStaticMarkup } from 'react-dom/server';
import { createReleaseChecker, checkedRelease, checkedFeed, STABLE_FEED_URL, compareStableRelease, parseVersion, validRepository } from '../server/updates/checker.mjs';
import { releaseConfig } from '../server/updates/release-config.mjs';
import { isSameOriginRequest } from '../server/auth/request-security.mjs';
import { readBoundedText } from '../server/http/request-body.mjs';

const config = { currentVersion: '1.2.0', repository: 'example/nodemail' };
// Explicit feed config: forks may point releaseConfig at their own Releases
// without breaking these checks of the feed mode itself.
const feedConfig = { currentVersion: releaseConfig.currentVersion, repository: '', feed: STABLE_FEED_URL };
const release = (tag = 'v1.3.0') => ({ tag_name: tag, draft: false, prerelease: false, published_at: '2026-10-08T00:00:00Z', body: 'Updates' });
const response = data => new Response(JSON.stringify(data));
const feed = (version = '1.3.0') => ({ schema: 1, product: 'NodeMail', channel: 'stable', version, publishedAt: '2026-10-08T00:00:00.000Z', notes: 'Public release notes' });

// The published stable.json is generated by the Documentation workflow and
// covered by release-feed.test.mjs; it is no longer a checked-in file.
test('metadata schema, product and stable channel are validated; arbitrary sources never get requested', async () => {
  for (const patch of [{ schema: 2 }, { product: 'Other' }, { channel: 'beta' }, { version: '1.3.0-beta' }, { notes: {} }, { publishedAt: 'invalid' }, { publishedAt: 1 }]) {
    assert.throws(() => checkedFeed({ ...feed(), ...patch }, config.currentVersion));
  }
  const parsed = checkedFeed({ ...feed(), url: 'javascript:alert(1)', token: 'secret', notes: '<script>x</script>' + 'x'.repeat(9000) }, config.currentVersion);
  assert.equal(parsed.url, 'https://github.com/Aoliao-aoliao/caocong-tempmail/releases/tag/v1.3.0'); assert.equal(parsed.notes.length, 8000); assert.equal(parsed.token, undefined);
  for (const source of ['http://127.0.0.1/', 'https://evil.test/', STABLE_FEED_URL + '?token=secret']) {
    const check = createReleaseChecker({ config: { currentVersion: '1.2.0', feed: source }, fetcher: () => assert.fail('network not allowed') });
    assert.equal((await check()).status, 'invalid-config');
  }
  assert.equal((await createReleaseChecker({ config: { ...feedConfig, repository: 'example/nodemail' }, fetcher: () => assert.fail('ambiguous source') })()).status, 'invalid-config');
});

test('metadata fetch failure is visible and cache/manual retry cannot turn an outage into up-to-date', async () => {
  let time = 0, fails = false, calls = 0;
  const check = createReleaseChecker({ config: feedConfig, now: () => time, fetcher: async () => {
    calls++; return fails ? new Response('<html>challenge</html>') : response(feed(releaseConfig.currentVersion));
  } });
  assert.equal((await check()).cached, false);
  assert.equal((await check({ force: true })).cached, true); assert.equal(calls, 1);
  time = 60000; fails = true;
  const result = await check({ force: true });
  assert.equal(result.status, 'unavailable'); assert.equal(result.latest.version, releaseConfig.currentVersion);
  assert.equal(result.lastSuccessAt, new Date(0).toISOString());
  assert.equal((await check()).cached, true); assert.equal(calls, 2);
  time += 60000; fails = false;
  assert.equal((await check({ force: true })).status, 'current'); assert.equal(calls, 3);
});

test('stable versions compare numerically, prerelease builds upgrade and malformed tags fail closed', () => {
  assert.equal(compareStableRelease('v1.10.0', '1.9.9'), 1);
  assert.equal(compareStableRelease('1.2.0', 'v1.2.0+build'), 0);
  assert.equal(compareStableRelease('1.2.0', '1.2.0-rc.1'), 1);
  assert.equal(compareStableRelease('1.2.0', '2.0.0'), -1);
  for (const version of ['main', 'v01.0.0', '1.0', '1.0.0-01', '1.0.0/evil', '99999999999.0.0']) assert.equal(parseVersion(version), null);
  assert.throws(() => compareStableRelease('1.3.0-rc.1', '1.2.0'));
});

test('release metadata rejects drafts and prereleases, never trusts remote links or unbounded notes', () => {
  const checked = checkedRelease({ ...release(), html_url: 'javascript:alert(1)', body: '<script>alert(1)</script>' + 'x'.repeat(9000) }, config.repository, config.currentVersion);
  assert.equal(checked.url, 'https://github.com/example/nodemail/releases/tag/v1.3.0');
  assert.equal(checked.notes.length, 8000);
  for (const patch of [{ draft: true }, { prerelease: true }, { draft: undefined }, { tag_name: 'main' }, { published_at: 'invalid' }]) {
    assert.throws(() => checkedRelease({ ...release(), ...patch }, config.repository, config.currentVersion));
  }
  for (const repo of ['https://evil.test/a', 'a/../../b', 'a/b?x=y', 'a/b#x', 'a/b/c', 'a/b.git', 'a/\nb']) assert.equal(validRepository(repo), false);
});

test('unconfigured or invalid source makes no network request and does not claim current', async () => {
  let calls = 0;
  for (const [repository, status] of [['', 'unconfigured'], ['http://127.0.0.1', 'invalid-config']]) {
    const check = createReleaseChecker({ config: { ...config, repository }, fetcher: async () => { calls++; } });
    assert.equal((await check({ force: true })).status, status);
  }
  assert.equal(calls, 0);
});

test('fixed GitHub request sends no secrets and distinguishes newer, equal and older releases', async () => {
  for (const [tag, status] of [['v1.3.0', 'available'], ['v1.2.0', 'current'], ['v1.1.0', 'ahead']]) {
    const check = createReleaseChecker({ config, fetcher: async (url, options) => {
      assert.equal(url, 'https://api.github.com/repos/example/nodemail/releases/latest');
      assert.equal(options.redirect, 'error'); assert.ok(options.signal);
      assert.equal(options.body, undefined);
      assert.deepEqual(Object.keys(options.headers).sort(), ['Accept', 'User-Agent', 'X-GitHub-Api-Version']);
      return response(release(tag));
    } });
    assert.equal((await check()).status, status);
  }
});

test('concurrent readers coalesce, automatic checks cache six hours and manual checks have a cooldown', async () => {
  let time = 0, calls = 0;
  const check = createReleaseChecker({ config, now: () => time, fetcher: async () => { calls++; return response(release()); } });
  const results = await Promise.all(Array.from({ length: 30 }, () => check()));
  assert.equal(calls, 1); assert.ok(results.every(r => r.status === 'available'));
  time = 59_999; await check({ force: true }); assert.equal(calls, 1);
  time = 60_000; await check({ force: true }); assert.equal(calls, 2);
  time += 6 * 3600_000 - 1; await check(); assert.equal(calls, 2);
  time++; await check(); assert.equal(calls, 3);
});

test('HTTP failures, invalid JSON, redirects, excessive body and timeout never report up to date', async () => {
  const fetchers = [
    ...[302, 404, 403, 429, 500].map(status => async () => new Response('', { status })),
    async () => new Response('{bad'),
    async () => new Response('x'.repeat(65537)),
    async () => { throw new Error('sensitive upstream detail'); },
    async (_url, { signal }) => new Promise((_resolve, reject) => signal.addEventListener('abort', () => reject(signal.reason))),
  ];
  const keepAlive = setInterval(() => {}, 1000);
  try {
    for (const fetcher of fetchers) {
      const result = await createReleaseChecker({ config, fetcher, timeoutMs: 10 })();
      assert.equal(result.status, 'unavailable'); assert.equal(result.latest, null);
      assert.ok(!JSON.stringify(result).includes('sensitive'));
    }
  } finally { clearInterval(keepAlive); }
});

test('failure backs off, preserves validated old notice and recovers after retry', async () => {
  let time = 0, fail = false, calls = 0;
  const check = createReleaseChecker({ config, now: () => time, fetcher: async () => { calls++; if (fail) throw Error('offline'); return response(release()); } });
  const initial = await check(); fail = true; time = 60_000;
  const failed = await check({ force: true });
  assert.equal(failed.status, 'unavailable'); assert.deepEqual(failed.latest, initial.latest);
  assert.equal(failed.lastSuccessAt, initial.lastSuccessAt);
  time += 15 * 60_000 - 1; await check(); assert.equal(calls, 2);
  time++; fail = false; assert.equal((await check()).status, 'available'); assert.equal(calls, 3);
});

async function loadTs(path, imports) {
  const source = await readFile(new URL(path, import.meta.url), 'utf8'), exports = {};
  runInNewContext(ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, jsx: ts.JsxEmit.ReactJSX, target: ts.ScriptTarget.ES2022 } }).outputText,
    { exports, require: name => { if (!(name in imports)) throw Error('Unexpected import ' + name); return imports[name]; }, Response, Request, URL, Buffer });
  return exports;
}

test('real admin auth guard protects GET/POST before any network check, including foreign origins', async () => {
  let user = null, calls = 0;
  const api = await loadTs('../server/http/api.mjs', {
    './request-body.mjs': { readBoundedText },
    '../auth/service.mjs': { getSessionUser: async () => user, sessionCookieName: 'session' },
    '../auth/request-security.mjs': { isSameOriginRequest },
  });
  const route = await loadTs('../src/pages/api/admin/updates.ts', {
    '../../../../server/http/api.mjs': api,
    '../../../../server/updates/checker.mjs': { checkForUpdates: async ({ force }) => { calls++; return { force }; } },
  });
  const context = (method, headers = {}) => ({ request: new Request('https://example.test/api/admin/updates', { method, headers: { 'sec-fetch-site': 'same-origin', ...headers } }), url: new URL('https://example.test/api/admin/updates'), cookies: { get: () => undefined } });
  assert.equal((await route.GET(context('GET'))).status, 401);
  user = { role: 'USER' }; assert.equal((await route.GET(context('GET'))).status, 403);
  user = { role: 'ADMIN' };
  assert.equal((await route.POST(context('POST', { origin: 'https://evil.test', 'content-type': 'application/json' }))).status, 403);
  assert.equal((await route.POST(context('POST'))).status, 415);
  assert.equal(calls, 0);
  for (const role of ['ADMIN', 'SUPER_ADMIN']) {
    user = { role };
    const get = await route.GET(context('GET')); assert.equal(get.status, 200);
    assert.equal(get.headers.get('cache-control'), 'no-store');
    assert.equal((await get.json()).update.force, false);
    assert.equal((await (await route.POST(context('POST', { 'content-type': 'application/json' }))).json()).update.force, true);
  }
  assert.equal(calls, 4);
});

test('update UI translates all states and treats remote notes as text, not active HTML', async () => {
  const catalog = JSON.parse(await readFile(new URL('../src/lib/ui-translations.json', import.meta.url), 'utf8'));
  const latest = checkedRelease({ ...release(), body: '<img src=x onerror=alert(1)><script>bad()</script>' }, config.repository, config.currentVersion);
  for (const locale of ['cn', 'en', 'tw']) {
    const module = await loadTs('../src/components/AdminUpdates.tsx', {
      react: React, 'react/jsx-runtime': jsx, '../styles/admin-updates.css': {},
      '../lib/useTranslator': { useTranslator: () => text => { if (locale === 'cn') return text; assert.ok(catalog[text]?.[locale], text); return catalog[text][locale]; } },
    });
    for (const status of ['available', 'current', 'ahead', 'unavailable', 'unconfigured', 'invalid-config']) {
      const update = { ...config, status, latest: ['unconfigured', 'invalid-config'].includes(status) ? null : latest };
      const html = renderToStaticMarkup(React.createElement(module.UpdateView, { update, busy: false, error: '', onCheck() {} }));
      assert.ok(!html.includes('<script>')); assert.ok(!html.includes('<img src=x'));
      if (update.latest) { assert.ok(html.includes('&lt;script&gt;')); assert.ok(html.includes('noopener noreferrer')); }
    }
  }
});
