import type { LibraryEntry } from './library';

export const useEntriesEn: LibraryEntry[] = [
  { slug: 'ai-signup', eyebrow: 'AI sign-ups', title: 'Give every AI tool a lasting, controllable address', summary: 'Disposable domains are often blocked. A long-lived alias keeps security notices arriving without exposing your real inbox.', cards: [['Codes are not the end', 'Recovery and security notices still need to reach you.'], ['One tool, one alias', 'A leak can be isolated to its source.'], ['Keep recovery open', 'The address remains available until you disable it.']], sectionTitle: 'When temp mail is the wrong fit', sectionBody: 'If an account may need recovery, billing or device verification later, use a long-lived alias instead of an expiring inbox.' },
  { slug: 'ecommerce', eyebrow: 'Ecommerce', title: 'Keep every storefront on its own notification address', summary: 'Separate stores, suppliers and tools while forwarding all important mail to one inbox.', cards: [['One store, one address', 'Every notification has a clear source.'], ['One inbox to check', 'No collection of separate mailbox accounts.'], ['Disable precisely', 'Closing one alias affects no other store.']], sectionTitle: 'Email is one isolation layer', sectionBody: 'Platforms may also evaluate devices, networks and payment details. Email aliases organize notifications and limit leaks; they do not override platform rules.' },
  { slug: 'airdrop', eyebrow: 'Campaigns', title: 'Keep campaign mail away from your primary inbox', summary: 'Use a dedicated address for confirmations and project updates, then close that route when the campaign ends.', cards: [['Isolate notices', 'High-volume promotion stays out of your main inbox.'], ['Trace the source', 'Each project receives its own address.'], ['End it cleanly', 'Disable the route when it is no longer useful.']], sectionTitle: 'An alias does not change eligibility', sectionBody: 'Email tools manage contact points. They must not be used to evade identity, device or participation limits.' },
  { slug: 'free-trials', eyebrow: 'Trials and offers', title: 'Use a disposable inbox when one code is truly enough', summary: 'A short-lived inbox fits a one-off download or confirmation. Accounts you keep should use an alias.', cards: [['Instant start', 'No extra account is needed.'], ['Automatic expiry', 'Future promotion loses its route.'], ['Clear purpose', 'Important accounts stay on lasting addresses.']], sectionTitle: 'Ask whether more mail will arrive', sectionBody: 'If billing, renewal or recovery mail will matter later, the address should not expire. Temp mail is for flows that genuinely end.' },
  { slug: 'social-accounts', eyebrow: 'Social accounts', title: 'Give every account a traceable address', summary: 'Separate login alerts, appeals and platform notices while delivering everything to one everyday inbox.', cards: [['Clear ownership', 'Each alias maps to one account.'], ['Central delivery', 'Important alerts do not scatter.'], ['Contain leaks', 'Only the affected alias is disabled.']], sectionTitle: 'Platform policy comes first', sectionBody: 'Aliases are for privacy and organization, not bulk abuse, impersonation or evading explicit account limits.' },
];

export const guideEntriesEn: LibraryEntry[] = [
  { slug: 'disposable-email-rejected', eyebrow: 'Troubleshooting', title: 'What to do when disposable email is rejected', summary: 'Domain reputation, age and mail history explain why some temporary addresses are blocked.', cards: [['Several providers fail', 'Sites may use the same domain lists.'], ['It worked yesterday', 'Blocklists change continuously.'], ['You still want privacy', 'A long-lived alias is usually more stable.']], sectionTitle: 'How sites detect temp mail', sectionBody: 'Common signals include domain lists, MX records, domain age and known disposable-mail patterns. A domain you control is often more durable.' },
  { slug: 'stop-spam-flood', eyebrow: 'Inbox hygiene', title: 'How to stop a continuing spam flood', summary: 'Find the exposed route and disable that alias instead of fighting every message individually.', cards: [['Find the source', 'A unique alias identifies the website.'], ['Close the route', 'Disable only the contaminated address.'], ['Keep normal mail', 'Other aliases continue unaffected.']], sectionTitle: 'Do not reuse one entry point', sectionBody: 'Once many services share an address, the leak is hard to locate. One alias per service keeps the map clear.' },
  { slug: 'find-who-leaked-your-email', eyebrow: 'Leak tracing', title: 'Find out who leaked your email address', summary: 'A unique address for each website makes the first unrelated message useful evidence.', cards: [['One site, one alias', 'Create a clean mapping.'], ['Keep a note', 'Record where and when it was used.'], ['Disable on discovery', 'Cut the leak without changing your real inbox.']], sectionTitle: 'The alias is the marker', sectionBody: 'When an address used at only one site receives unrelated marketing, the possible source is already narrow.' },
];

export const alternativeEntriesEn: LibraryEntry[] = [
  { slug: 'firefox-relay', eyebrow: 'Product comparison', title: 'How to choose an anonymous alias service', summary: 'Compare free limits, custom domains, attachments, delivery and portability.', cards: [['Free allowance', 'Check alias and attachment limits.'], ['Custom domains', 'Ownership makes migration easier.'], ['Data policy', 'Know which logs and messages are retained.']], sectionTitle: 'Address count is not everything', sectionBody: 'For long-term use, domain control, delivery, export options and disable rules matter more than a large free number.' },
  { slug: 'simplelogin', eyebrow: 'Product comparison', title: 'Where email alias services differ', summary: 'Compare forwarding, multiple recipients, custom domains and day-to-day controls.', cards: [['Forwarding', 'Check attachments and sender information.'], ['Domain support', 'Look for catch-all and multiple domains.'], ['Management', 'Find and disable an alias quickly.']], sectionTitle: 'Plan for migration early', sectionBody: 'With your own domain, changing providers can be as simple as updating DNS while every address stays the same.' },
  { slug: 'apple-hide-my-email', eyebrow: 'Product comparison', title: 'System-level hidden email or an independent alias', summary: 'Built-in tools are convenient; independent services usually offer finer controls and better portability.', cards: [['Ecosystem lock-in', 'Built-in tools follow one account system.'], ['Cross-platform use', 'Independent aliases work on any device.'], ['Domain ownership', 'Your domain keeps options open.']], sectionTitle: 'Choose for the lifetime of the account', sectionBody: 'A built-in option is simple inside one ecosystem. Long-term cross-platform use benefits from a portable domain.' },
  { slug: 'temp-mail-services', eyebrow: 'Product comparison', title: 'What to compare in temporary mail services', summary: 'Look beyond domain count to expiry, delivery, attachments, privacy and abuse controls.', cards: [['Expiry', 'The window must cover the whole task.'], ['Delivery', 'Codes and attachments need to arrive reliably.'], ['Destruction', 'Expired content should actually be removed.']], sectionTitle: 'Temporary and lasting mail are different products', sectionBody: 'A disposable inbox fits one-off flows. It cannot replace an address needed for account recovery, billing or lasting security notices.' },
];
