import {useEffect,useRef,useState} from 'react';
type Config={origin:string;enabled:boolean;configured:boolean;canEdit:boolean;pid:string;keyConfigured:boolean;notifyUrl:string;returnUrl:string};
export default function GmpayPaymentStatus(){
 const [state,setState]=useState<Config|null>(null),[secret,setSecret]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const lock=useRef(false);
 useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);fetch('/api/admin/gmpay-payment',{signal:controller.signal}).then(async r=>{const p=await r.json();if(!r.ok||!p.ok)throw Error(p.message||'读取失败。');setState(p.config);}).catch(e=>setMessage(controller.signal.aborted?'配置读取超时，请刷新后重试。':e.message||'读取失败。')).finally(()=>clearTimeout(timer));return()=>{clearTimeout(timer);controller.abort();};},[]);
 async function save(e:React.FormEvent){e.preventDefault();if(!state?.canEdit||lock.current)return;lock.current=true;setBusy(true);setMessage('正在保存…');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch('/api/admin/gmpay-payment',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({pid:state.pid,secretKey:secret,enabled:state.enabled}),signal:controller.signal});const p=await r.json();if(!r.ok||!p.ok)throw Error(p.message||'保存失败。');setState(p.config);setSecret('');setMessage('USDT 支付配置已保存。');}catch(e){setMessage(controller.signal.aborted?'保存结果待核实，请刷新读取配置后再试。':e instanceof Error?e.message:'保存失败。');}finally{clearTimeout(timer);lock.current=false;setBusy(false);}}
 return <section className="admin-panel nl-payment"><header><div><h2>USDT / TRC20 支付</h2><p>GM Pay / EPUSDT v2 · 沿用已保存的美元充值档位</p></div></header>
 {!state?<div className="gmpay-status-content"><p role="status">{message||'正在读取支付配置…'}</p></div>:<form onSubmit={e=>void save(e)}><fieldset className="nl-settings-fields" disabled={busy||!state.canEdit}>
 <div className="nl-form-grid"><label>商户 PID<input value={state.pid||''} autoComplete="off" onChange={e=>setState({...state,pid:e.target.value})} required maxLength={64}/></label><label>API 密钥 secret_key<input type="password" value={secret} autoComplete="new-password" onChange={e=>setSecret(e.target.value)} maxLength={1024} placeholder={state.keyConfigured?'已配置；留空保持原密钥':'填写 GMPay 后台 API 密钥'}/><small>更换 PID 时需同时填写对应密钥。仅后端加密保存，不回显。</small></label></div>
 <div className="nl-settings-switches"><label className="nl-check"><input type="checkbox" checked={state.enabled} onChange={e=>setState({...state,enabled:e.target.checked})}/>启用 USDT 支付</label><p>网关 {state.origin || "未配置"} · TRON 主网 · 仅 USDT / TRC20。本站不创建人工 USDT 待支付订单。</p></div></fieldset>
 <details><summary>回调地址与支付说明</summary><p className="nl-url">到账通知：{state.notifyUrl}</p><p className="nl-url">付款返回：{state.returnUrl}</p><p>套餐以 USD 标价；用户必须支付网关给出的精确 USDT 数量。已验签回调核对订单、金额、资产与网络后才入账，重复通知不会重复发放积分。</p></details>
 {!state.canEdit&&<p>只有超级管理员可以修改商户凭证与支付开关。</p>}<div className="nl-settings-save"><p className="nl-settings-message" role="status">{message||(!state.configured?'尚未配置商户凭证。':state.enabled?'USDT 支付已启用。':'凭证已配置，支付尚未启用。')}</p>{state.canEdit&&<button type="submit" className="nl-button" disabled={busy}>{busy?'正在保存…':'保存 USDT 配置'}</button>}</div>
 </form>}</section>;
}
