import {AdminTabNav,AdminTabPanel,useAdminTabs} from './AdminTabs';
import RelayAliasSettings, {type AliasAccount} from './RelayAliasSettings';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import '../styles/relay-admin.css';
import MicrosoftRelayConfig, {microsoftRequest,type MicrosoftConfig} from './MicrosoftRelayConfig';

type Account = {
  id:string; provider:string; email:string; suffix:string; imap_host:string; imap_port:number;
  imap_secure:boolean; username:string; status:string; max_aliases:number; last_uid:number;
  last_error:string|null; last_checked_at:string|null; credentialConfigured:boolean; oauthStatus?:string|null; extraAddresses?:string[];
};
type CleanupStatus = { enabled:boolean; pending:number; completed:number; skipped:number };
const empty={id:'',provider:'GMAIL',email:'',suffix:'gmail.com',imapHost:'imap.gmail.com',imapPort:993,imapSecure:true,username:'',credential:'',maxAliases:500};

export default function RelayAdmin({initialAccounts,initialCleanup,initialMicrosoftConfig,canConfigureMicrosoft}:{initialAccounts:Account[];initialCleanup:CleanupStatus;initialMicrosoftConfig:MicrosoftConfig;canConfigureMicrosoft:boolean}){
  const [active,setActive]=useAdminTabs('accounts');
  useEffect(()=>{if(new URLSearchParams(location.search).has('microsoft'))setActive('microsoft');},[]);
  const aliasLock=useRef(false);
  const aliasChange=async(item:AliasAccount,address:string,enabled:boolean,confirmed:boolean)=>{if(busy||aliasLock.current)return;aliasLock.current=true;setBusy('alias:'+item.id);setMessage('');try{await send({action:'alias-setting',id:item.id,address,enabled,confirmed});await reload();setMessage(enabled?'别名已启用，前台可以使用对应后缀生成地址。':'已停止该别名的新分配，已有邮箱继续收信。');}catch(error){setMessage(error instanceof Error?error.message:'别名设置失败');}finally{setBusy('');aliasLock.current=false;}};
  const [accounts,setAccounts]=useState(initialAccounts); const [cleanup,setCleanup]=useState(initialCleanup); const [form,setForm]=useState<any>(empty); const [busy,setBusy]=useState(''); const [message,setMessage]=useState('');
  const authorizeLock=useRef(false); const [authorizationMessage,setAuthorizationMessage]=useState<{id:string;message:string}|null>(null);
  const reload=async()=>{const response=await fetch('/api/admin/relays',{headers:{accept:'application/json'}});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.message||'读取失败');setAccounts(result.accounts||[]);if(result.cleanup)setCleanup(result.cleanup);};
  const send=async(body:any)=>{const response=await fetch('/api/admin/relays',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await response.json().catch(()=>null);if(!response.ok||!result?.ok)throw new Error(result?.message||'操作失败');return result.result;};
  const authorize=async(item:Account)=>{
    if(busy||authorizeLock.current)return;
    authorizeLock.current=true;setBusy(`authorize:${item.id}`);setMessage('');setAuthorizationMessage(null);
    try{
      const result=await microsoftRequest({action:'authorize',id:item.id});
      const url=new URL(result.result.url);
      if(url.origin!=='https://login.microsoftonline.com'||url.pathname!=='/consumers/oauth2/v2.0/authorize')throw new Error('授权地址无效');
      location.assign(url.href);
    }catch(e){setAuthorizationMessage({id:item.id,message:e instanceof Error?e.message:'授权失败，请重试。'});setBusy('');authorizeLock.current=false;}
  };
  const provider=(value:string)=>{const preset=value==='GMAIL'?{suffix:'gmail.com',imapHost:'imap.gmail.com'}:value==='OUTLOOK'?{suffix:'outlook.com',imapHost:'outlook.office365.com'}:{suffix:'',imapHost:''};setForm({...form,provider:value,...preset,...(value==='OUTLOOK'?{imapPort:993,imapSecure:true,username:form.email,credential:'',suffix:form.email.split('@')[1]||'outlook.com'}:{})});};
  const edit=(item:Account)=>{setActive("form");setForm({id:item.id,provider:item.provider,email:item.email,suffix:item.suffix,imapHost:item.imap_host,imapPort:item.imap_port,imapSecure:item.imap_secure,username:item.username,credential:'',maxAliases:item.max_aliases,...(item.provider==='OUTLOOK'?{username:item.email,suffix:item.email.split('@')[1]||'',imapHost:'outlook.office365.com',imapPort:993,imapSecure:true}:{})});};
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy('save');setMessage('');try{await send({action:'save',...form});await reload();setForm(empty);setActive('accounts');setMessage('中继账号已安全保存。下一步请检测连接，成功后再启用。');}catch(error){setMessage(error instanceof Error?error.message:'保存失败');}finally{setBusy('');}};
  const action=async(item:Account,kind:'test'|'status',status?:string)=>{setBusy(`${kind}:${item.id}`);setMessage('');try{await send({action:kind,id:item.id,status});await reload();setMessage(kind==='test'?'IMAP 真实连接检测成功，可以启用该账号。':'账号状态已更新。');}catch(error){setMessage(error instanceof Error?error.message:'操作失败');await reload().catch(()=>{});}finally{setBusy('');}};
  const testAll=async()=>{setBusy('test-all');setMessage('');try{const result=await send({action:'test-all'});await reload();setMessage(`检测完成：共 ${result.checked} 个账号，${result.healthy} 个正常，${result.failed} 个异常。`);}catch(error){setMessage(error instanceof Error?error.message:'批量检测失败');await reload().catch(()=>{});}finally{setBusy('');}};
  const toggleCleanup=async()=>{setBusy('cleanup');setMessage('');try{const result=await send({action:'cleanup-setting',enabled:!cleanup.enabled});setCleanup(result);setMessage(result.enabled?'到期自动清理已开启。':'到期自动清理已关闭。');}catch(error){setMessage(error instanceof Error?error.message:'设置失败');}finally{setBusy('');}};
  const useExample=(kind:'GMAIL'|'OUTLOOK'|'CUSTOM')=>{setActive('form');const sample=kind==='GMAIL'?{provider:'GMAIL',email:'yourname@gmail.com',suffix:'gmail.com',imapHost:'imap.gmail.com',imapPort:993,imapSecure:true,username:'yourname@gmail.com',credential:'',maxAliases:500}:kind==='OUTLOOK'?{provider:'OUTLOOK',email:'yourname@outlook.com',suffix:'outlook.com',imapHost:'outlook.office365.com',imapPort:993,imapSecure:true,username:'yourname@outlook.com',credential:'',maxAliases:500}:{provider:'CUSTOM',email:'mail@example.com',suffix:'example.com',imapHost:'imap.example.com',imapPort:993,imapSecure:true,username:'mail@example.com',credential:'',maxAliases:500};setForm({id:'',...sample});setMessage('示例已填入。请替换为你的真实账号，再按服务商使用应用密码或微软 OAuth2 授权。');};

  return <div className="relay-admin-page relay-admin-tabbed"><section className="admin-panel relay-admin-intro"><div><span>RELAY MAIL</span><h2>中继邮箱账号池</h2><p>添加真实 Gmail / Outlook 收信账号。Gmail／自定义 IMAP 使用加密保存的应用密码；微软邮箱使用 OAuth2 授权。</p></div><aside><b>{accounts.filter(x=>x.status==='ACTIVE').length}</b><small>个可用账号</small></aside></section>
<AdminTabNav scope="relay" tabs={[{"id":"accounts","label":"账号列表"},{"id":"aliases","label":"别名配置"},{"id":"form","label":"添加账号"},{"id":"microsoft","label":"微软授权"},{"id":"guide","label":"配置指南"},{"id":"cleanup","label":"到期清理"}]} active={active} onChange={setActive}/>
{message&&<p className="relay-admin-message" role="status">{message}</p>}
<AdminTabPanel scope="relay" id="accounts" active={active}><section className="admin-panel relay-account-list"><header><div><h2>账号列表</h2><p>只有真实检测成功并启用的账号会参与中继地址分配。</p></div><button type="button" className="relay-test-all" disabled={Boolean(busy)||!accounts.length} onClick={testAll}>{busy==='test-all'?'检测中…':'检测全部'}</button></header>{accounts.length?<div className="relay-account-table"><div className="relay-account-head"><span>账号</span><span>服务商 / 后缀</span><span>健康状态</span><span>容量</span><span>操作</span></div>{accounts.map(item=><article key={item.id}><span><strong>{item.email}</strong><small>{item.imap_host}:{item.imap_port} · {item.imap_secure?'TLS':'非 TLS'}</small></span><span><b>{item.provider}</b><small>{item.suffix}</small></span><span><span><i className={`relay-health ${item.status.toLowerCase()}`}></i>{item.status==='ACTIVE'?'正常启用':item.status==='ERROR'?'连接异常':'尚未启用'}</span><small>{item.last_error||(item.last_checked_at?'真实连接已验证':'尚未检测')}</small><small>检测时间：{item.last_checked_at?new Date(item.last_checked_at).toLocaleString('zh-CN',{hour12:false,timeZone:"Asia/Shanghai"}):'—'}</small></span><span>{item.max_aliases}<small>已同步 UID {item.last_uid}</small></span><span className="relay-row-actions">{item.provider==='OUTLOOK'&&<>{authorizationMessage?.id===item.id&&<small role="alert">{authorizationMessage.message}</small>}<small>{item.oauthStatus==='AUTHORIZED'?'OAuth2 已授权':item.oauthStatus==='REAUTH_REQUIRED'?'授权失效，需要重新授权':'尚未微软授权'}</small><a className="relay-authorize-link" href={`/api/admin/microsoft/authorize?id=${encodeURIComponent(item.id)}`} aria-disabled={Boolean(busy)} onClick={event=>{event.preventDefault();void authorize(item);}}>{busy===`authorize:${item.id}`?'正在跳转…':item.oauthStatus==='NOT_AUTHORIZED'?'微软授权':'重新授权'}</a></>}<button onClick={()=>edit(item)}>编辑</button><button disabled={Boolean(busy)} onClick={()=>action(item,'test')}>{busy===`test:${item.id}`?'检测中…':'检测连接'}</button><button disabled={Boolean(busy)} onClick={()=>action(item,'status',item.status==='ACTIVE'?'DISABLED':'ACTIVE')}>{busy===`status:${item.id}`?'处理中…':item.status==='ACTIVE'?'停用':'检测并启用'}</button></span></article>)}</div>:<div className="admin-empty-state">尚未添加中继账号。请先套用上方示例并替换为真实资料，保存、检测并启用后，用户端才会显示可用后缀。</div>}</section></AdminTabPanel>
<AdminTabPanel scope="relay" id="aliases" active={active}><RelayAliasSettings accounts={accounts} busy={busy} onChange={aliasChange}/></AdminTabPanel>
<AdminTabPanel scope="relay" id="form" active={active}><section className="admin-panel relay-admin-form"><header><div><h2>{form.id?'编辑中继账号':'添加中继账号'}</h2><p>Gmail／自定义 IMAP 填应用密码；微软邮箱保存后点击授权，不填网页登录密码。</p></div>{form.id&&<button type="button" onClick={()=>setForm(empty)}>取消编辑</button>}</header><form onSubmit={submit}><label>服务商<select value={form.provider} onChange={e=>provider(e.target.value)}><option value="GMAIL">Gmail</option><option value="OUTLOOK">Outlook</option><option value="CUSTOM">自定义 IMAP</option></select></label><label>真实邮箱账号<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value,username:form.provider==='OUTLOOK'?e.target.value:form.username||e.target.value,...(form.provider==='OUTLOOK'?{suffix:e.target.value.split('@')[1]||''}:{})})} placeholder="account@gmail.com"/></label><label>对外后缀<input required readOnly={form.provider==='OUTLOOK'} value={form.suffix} onChange={e=>setForm({...form,suffix:e.target.value})}/></label><label>IMAP 服务器<input required readOnly={form.provider==='OUTLOOK'} value={form.imapHost} onChange={e=>setForm({...form,imapHost:e.target.value})}/></label><label>端口<input type="number" min="1" max="65535" required readOnly={form.provider==='OUTLOOK'} value={form.imapPort} onChange={e=>setForm({...form,imapPort:Number(e.target.value)})}/></label><label>IMAP 用户名<input required readOnly={form.provider==='OUTLOOK'} value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>应用密码 / IMAP 凭据<input type="password" required={!form.id&&form.provider!=='OUTLOOK'} disabled={form.provider==='OUTLOOK'} value={form.credential} onChange={e=>setForm({...form,credential:e.target.value})} placeholder={form.provider==='OUTLOOK'?'微软邮箱保存后通过 OAuth2 授权':form.id?'留空则保留原凭据':'请输入应用专用密码'}/></label><label>别名容量<input type="number" min="1" max="100000" required value={form.maxAliases} onChange={e=>setForm({...form,maxAliases:Number(e.target.value)})}/></label><label className="relay-check"><input type="checkbox" disabled={form.provider==='OUTLOOK'} checked={form.imapSecure} onChange={e=>setForm({...form,imapSecure:e.target.checked})}/>启用 TLS 安全连接</label><button className="primary-action" disabled={Boolean(busy)}>{busy==='save'?'正在保存…':'保存账号'}</button></form>{message&&<p className="relay-admin-message" role="status">{message}</p>}</section></AdminTabPanel>
<AdminTabPanel scope="relay" id="microsoft" active={active}><MicrosoftRelayConfig initialConfig={initialMicrosoftConfig} canConfigure={canConfigureMicrosoft}/></AdminTabPanel>
<AdminTabPanel scope="relay" id="guide" active={active}><section className="relay-admin-guide"><header><div><strong>配置示例与检测流程</strong><small>套用后请替换为自己的真实账号，示例不会自动保存</small></div><button type="button" disabled={Boolean(busy)||!accounts.length} onClick={testAll}>{busy==='test-all'?'正在检测全部…':'检测全部账号'}</button></header><div className="relay-example-grid"><article><b>Gmail 示例</b><code>yourname@gmail.com</code><code>imap.gmail.com : 993</code><span>开启两步验证并创建应用专用密码，不能填写网页登录密码。</span><button type="button" onClick={()=>useExample('GMAIL')}>套用 Gmail 示例</button></article><article><b>Outlook 示例</b><code>yourname@outlook.com</code><code>outlook.office365.com : 993</code><span>先保存账号，再点击微软授权；无需填写密码。支持 Outlook.com／Hotmail 个人账号。</span><button type="button" onClick={()=>useExample('OUTLOOK')}>套用 Outlook 示例</button></article><article><b>自定义 IMAP</b><code>mail@example.com</code><code>imap.example.com : 993</code><span>向邮箱服务商确认 IMAP 地址、TLS 端口、用户名和应用密码。</span><button type="button" onClick={()=>useExample('CUSTOM')}>套用自定义示例</button></article></div><ol><li><b>1. 保存账号</b><span>凭据加密保存，默认不会直接投入使用。</span></li><li><b>2. 检测连接</b><span>真实登录 IMAP 并打开 INBOX，不是只检查格式。</span></li><li><b>3. 检测并启用</b><span>成功后用户端才会出现相应邮箱后缀。</span></li></ol></section></AdminTabPanel>
<AdminTabPanel scope="relay" id="cleanup" active={active}><section className="admin-panel relay-cleanup-setting"><div><h2>到期原邮件清理</h2><p>访客或注册用户的中继邮箱到期后，本地旧邮件按现有规则删除，并将上游邮箱中对应原邮件移入垃圾箱。只处理已成功保存且能精确匹配的邮件，不永久删除。</p><small>待处理 {cleanup.pending} · 已完成 {cleanup.completed} · 安全跳过 {cleanup.skipped}</small></div><button type="button" className={cleanup.enabled?'is-enabled':''} disabled={Boolean(busy)} onClick={toggleCleanup}>{busy==='cleanup'?'正在保存…':cleanup.enabled?'已开启':'已关闭'}</button></section></AdminTabPanel></div>;
}
