#!/usr/bin/env bash
# Invoked only after the GitHub production gate and operator-created READY marker.
set -euo pipefail
umask 077
DEPLOY_ROOT=/opt/nodemail
sha=${1:?Expected release commit SHA}
[[ "$sha" =~ ^[0-9a-f]{40}$ ]] || { echo 'Invalid release SHA' >&2; exit 1; }
cd "$DEPLOY_ROOT"
test -f .deploy/READY
test -f .env
test -f docker-compose.yml
test -f .deploy/site-profile.json
command -v flock >/dev/null
command -v python3 >/dev/null
command -v docker >/dev/null
exec 9>.deploy/deploy.lock
flock -n 9 || { echo 'Another NodeMail deployment holds the lock' >&2; exit 1; }

incoming="$DEPLOY_ROOT/.deploy/incoming/$sha"
cd "$incoming"
sha256sum -c nodemail-image.tar.gz.sha256
docker load -i nodemail-image.tar.gz >/dev/null
image="nodemail:$sha"
docker image inspect "$image" >/dev/null
project=$(docker inspect nodemail --format '{{index .Config.Labels "com.docker.compose.project"}}')
[[ "$project" =~ ^[a-z0-9][a-z0-9_-]*$ ]] || { echo 'Invalid existing Compose project' >&2; exit 1; }
test "$(docker info --format '{{.Architecture}}')" = x86_64
python3 "$incoming/deploy_preflight.py" "$image" "$project"
# Runtime repairs can live in the container writable layer. A tag of .Image
# would lose them on rollback. Snapshot that layer before replacing the service;
# Docker excludes mounted database/attachments/TLS, which remain unchanged.
rollback_tag="nodemail:rollback-${sha}-$(date +%s)-$$"
python3 "$incoming/snapshot_rollback.py" "$rollback_tag" "$project"
# CLI commit output may be a manifest digest; health checks use the inspected
# image identity, as Docker inspect reports it for running containers.
old_image=$(docker image inspect "$rollback_tag" --format '{{.Id}}')
[[ "$old_image" =~ ^sha256:[0-9a-f]{64}$ ]] || { echo 'Rollback snapshot has invalid image identity' >&2; exit 1; }
echo "NodeMail rollback snapshot $old_image"

state=$(mktemp -d "$DEPLOY_ROOT/.deploy/transaction.XXXXXX")
override="$state/candidate.yml"
rollback="$state/rollback.yml"
write_override() {
  local target=$1 selected_image=$2
  cat > "$target" <<EOF
services:
  nodemail:
    image: $selected_image
    # Do not run the Dockerfile's db:init command against production.
    command: ["node", "server/mail/process-manager.mjs"]

EOF
}
write_override "$override" "$image"
python3 "$incoming/site_profile.py" "$override" "$DEPLOY_ROOT/.deploy/site-profile.json" "$DEPLOY_ROOT/.deploy/active.yml"
if [[ -f "$DEPLOY_ROOT/.deploy/active.yml" && ! -L "$DEPLOY_ROOT/.deploy/active.yml" ]]; then
  cp "$DEPLOY_ROOT/.deploy/active.yml" "$rollback"
  # Previous release overlay was generated by this script with an image field.
  sed -i "s|^    image: .*|    image: $rollback_tag|" "$rollback"
else
  write_override "$rollback" "$rollback_tag"
fi
compose() {
  local selected=$1
  shift
  docker compose --project-directory "$DEPLOY_ROOT" --env-file "$DEPLOY_ROOT/.env" \
    -p "$project" -f "$DEPLOY_ROOT/docker-compose.yml" -f "$selected" "$@"
}
wait_healthy() {
  local expected=$1
  for ((attempt=0; attempt<36; attempt++)); do
    local actual status running restarting
    actual=$(docker inspect nodemail --format '{{.Image}}' 2>/dev/null) || actual=''
    status=$(docker inspect nodemail --format '{{if .State.Health}}{{.State.Health.Status}}{{end}}' 2>/dev/null) || status=''
    running=$(docker inspect nodemail --format '{{.State.Running}}' 2>/dev/null) || running=''
    restarting=$(docker inspect nodemail --format '{{.State.Restarting}}' 2>/dev/null) || restarting=''
    if [[ "$actual" = "$expected" && "$status" = healthy && "$running" = true && "$restarting" = false ]]; then return 0; fi
    sleep 5
  done
  return 1
}
verify_services() {
  docker exec -i nodemail node --input-type=module <<'HEALTH_SCRIPT'
import { createConnection } from 'node:net';
const health = await fetch('http://127.0.0.1:4321/api/health', { signal: AbortSignal.timeout(10000) });
if (!health.ok || (await health.json()).ok !== true) throw new Error('NodeMail HTTP/database health failed');
const origins = [process.env.NODEMAIL_PUBLIC_ORIGIN, process.env.NODEMAIL_SITE_ORIGIN].filter(Boolean);
if (!origins.length) throw new Error('Deployment origins are not configured');
for (const url of origins) {
  const response = await fetch(url, { signal: AbortSignal.timeout(15000) });
  if (!response.ok || !(await response.text()).includes('NodeMail')) throw new Error(`NodeMail website check failed: ${url}`);
}
await new Promise((resolve, reject) => {
  const socket = createConnection({ host: '127.0.0.1', port: 2525 });
  let buffer = '';
  const finish = error => { socket.destroy(); error ? reject(error) : resolve(); };
  socket.setTimeout(5000);
  socket.once('error', finish);
  socket.once('timeout', () => finish(new Error('NodeMail SMTP greeting timeout')));
  socket.on('data', data => {
    buffer += data.toString();
    if (buffer.includes('\n')) finish(/^220[ -]/.test(buffer) ? null : new Error('NodeMail SMTP greeting failed'));
  });
  socket.once('end', () => { if (!buffer.includes('\n')) finish(new Error('NodeMail SMTP closed before greeting')); });
});
console.info('Verified NodeMail: HTTP/database health, local and public websites, SMTP 220 greeting');
HEALTH_SCRIPT
}
changed=false
committed=false
finish() {
  local result=$?
  trap - EXIT INT TERM
  if [[ "$changed" = true && "$committed" = false ]]; then
    echo 'Deployment failed; restoring previous image' >&2
    if compose "$rollback" up -d --no-deps --no-build --pull never --force-recreate --timeout 30 nodemail \
      && wait_healthy "$old_image" && verify_services; then
      cp "$rollback" "$DEPLOY_ROOT/.deploy/active.yml.tmp"
      mv "$DEPLOY_ROOT/.deploy/active.yml.tmp" "$DEPLOY_ROOT/.deploy/active.yml"
      echo 'Rollback healthy; deployment remains failed' >&2
    else
      echo "ROLLBACK FAILED: operator intervention required; recovery files: $state" >&2
    fi
    result=1
  fi
  # Retain transaction overlays and images for recovery; no data/config deletion.
  exit "$result"
}
trap finish EXIT
trap 'exit 130' INT
trap 'exit 143' TERM
trap 'exit 129' HUP
candidate_id=$(docker image inspect "$image" --format '{{.Id}}')
changed=true
compose "$override" up -d --no-deps --no-build --pull never --force-recreate --timeout 30 nodemail
wait_healthy "$candidate_id" || { echo 'Candidate failed HTTP/database or SMTP healthcheck' >&2; exit 1; }
verify_services || { echo 'Candidate failed fresh website or SMTP validation' >&2; exit 1; }
cp "$rollback" "$DEPLOY_ROOT/.deploy/previous.yml.tmp"
mv "$DEPLOY_ROOT/.deploy/previous.yml.tmp" "$DEPLOY_ROOT/.deploy/previous.yml"
cp "$override" "$DEPLOY_ROOT/.deploy/active.yml.tmp"
mv "$DEPLOY_ROOT/.deploy/active.yml.tmp" "$DEPLOY_ROOT/.deploy/active.yml"
printf '%s\n' "$sha" > "$DEPLOY_ROOT/.deploy/current-sha.tmp"
mv "$DEPLOY_ROOT/.deploy/current-sha.tmp" "$DEPLOY_ROOT/.deploy/current-sha"
committed=true
# Enable retention only after success: initial automatic rollback still has all
# legacy receipts. A later rollback image already reads the independent tables.
docker exec -w /app nodemail node --input-type=module -e "const m=await import('./server/admin/audit-retention.mjs');try{await m.activateAuditRetention();}finally{await m.closeDatabasePool();}" || echo 'WARNING: audit retention remains disabled; deployment stays successful'
echo "NodeMail release $sha is healthy"
echo "NodeMail running image $candidate_id"

# Success is committed before best-effort cleanup; cleanup cannot trigger rollback.
echo 'NodeMail release cleanup: /opt filesystem before'
df -h "$DEPLOY_ROOT" || echo 'WARNING: could not read filesystem space'
python3 "$incoming/cleanup_releases.py" "$sha" "$rollback_tag" || echo 'WARNING: NodeMail release cleanup failed; deployment remains successful'
echo 'NodeMail release cleanup: /opt filesystem after'
df -h "$DEPLOY_ROOT" || echo 'WARNING: could not read filesystem space'
